icons = "awesome"

[theme]
name = "space-villain"
[theme.overrides]
separator = ""

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "time"
interval = 60
format = "%a %d %B - %R"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"


