icons = "/home/y13/common/i3status-rust/files/icons/awesome.toml"

[theme]
name = "/home/y13/common/i3status-rust/files/themes/space-villain.toml"
[theme.overrides]
separator = ""


# [[block]]
# block = "disk_space"
# path = "/home"
# alias = "~/"
# info_type = "available"
# unit = "GB"
# interval = 20
# warning = 20.0
# alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_total_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"


[[block]]
block = "time"
interval = 60
format = "%a %d %B - %R"
