icon_format = "{icon}"

[theme]
theme = "/home/y13/personal/standard_config/i3status-rust/files/themes/space-villain.toml"
[theme.overrides]
separator = ""

[icons]
icons = "/home/y13/personal/standard_config/i3status-rust/files/icons/emoji.toml"


[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90


[[block]]
block = "sound"


[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%R %d/%m/%Y ') "

[[block]]
block = "net"
format = " $icon $ssid"

