default: 
		@echo "Please choose one of the following target: update, install."
		@exit 1

update:
		@cp ~/.tmux.conf ./tmux.conf
		@echo "Updated config files present in the repo."

install:
		@cp ./tmux.conf ~/.tmux.conf
		@echo "Installed tmux config files"


